# Generated by Django 4.2.30 on 2026-09-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_promotion_product_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
